### ISSUE TITLE
Deploy Jupyter Book

### ISSUE THREAD

**Issue by msoltadeo** [worldbank/alternative-data-for-crisis#12]
This issue tracks enabling the deployment for the DEC course to [GitHub Pages](https://pages.github.com/). Initially, the Jupyter Book will be built onto the `gh-pages` privately. It will be closed by #39. 

```[tasklist]
### Tasks
- [ ] #11 
- [ ] #3 
- [ ] #5
- [ ] #7 
- [ ] https://github.com/datapartnership/alternative-data-for-crisis/issues/29
- [ ] https://github.com/datapartnership/alternative-data-for-crisis/issues/19
- [ ] https://github.com/datapartnership/alternative-data-for-crisis/issues/21
- [ ] https://github.com/datapartnership/alternative-data-for-crisis/issues/15
```
