### ISSUE TITLE
Switch to Git Flow and Release Management Workflow

### ISSUE THREAD

**Issue by g4brielvs** [worldbank/alternative-data-for-crisis#51]
Our current simplified Git workflow is easy to understand, but it’s limited as a project grows in complexity. To better manage development and releases, I propose we adopt [Git Flow](https://www.gitkraken.com/learn/git/git-flow), which provides a more organized branching structure, and release flows for smoother, more controlled releases.

- This change will require some initial setup and training, but it will lead to a more efficient and manageable workflow in the long run.
- Existing branches and workflows can be phased out gradually to minimize disruption.

```[tasklist]
### Tasks
- [ ] Implement the new branching strategy and update all relevant documentation.
- [x] Create https://github.com/datapartnership/alternative-data-for-crisis/tree/develop
- [ ] Make develop branch default
```

**Comment by g4brielvs** [comment]
Just created https://github.com/datapartnership/alternative-data-for-crisis/tree/develop.

**Comment by msoltadeo** [comment]
@g4brielvs, thank you very much! This is super useful!

**Comment by g4brielvs** [comment]
@msoltadeo Apologies it wasn't very clear from the start that the branching strategy inherited from the [Template](https://worldbank.github.io/template/README.html) was the [GitHub Flow](https://docs.github.com/en/get-started/using-github/github-flow).
